# Generated by Django 2.2.16 on 2020-10-27 07:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=100, verbose_name='Ник инвестора')),
                ('platform_roules', models.BooleanField(default=False, verbose_name='Ознакомление с правилами платформы и принятие рисков')),
                ('tax_roles', models.BooleanField(default=False, verbose_name='Подтверждение налогового статуса')),
                ('autoinvestor_rules', models.BooleanField(default=False, verbose_name='Согласие с использованием автоинвестирования')),
            ],
        ),
        migrations.CreateModel(
            name='QualificationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_status', models.CharField(choices=[('yes', 'квалификация подтверждена'), ('no', 'квалификация не подтверждена'), ('check', 'документы на проверке')], default='no', max_length=5, verbose_name='Общий статус квалификации пользователя')),
            ],
            options={
                'verbose_name_plural': 'Qualification status',
            },
        ),
        migrations.CreateModel(
            name='QualificationDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_refuse', models.BooleanField(default=False, verbose_name='Отказ от квалификации')),
                ('economic_education', models.FileField(blank=True, null=True, upload_to='files', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Высшее экономическое образование с правом аттестации профучастника')),
                ('securities_value', models.FileField(blank=True, null=True, upload_to='files', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Общая стоимость ценных бумаг')),
                ('economic_work_experience', models.FileField(blank=True, null=True, upload_to='files', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Опыт работы в финансовой компании')),
                ('deposit_and_metals', models.FileField(blank=True, null=True, upload_to='files', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Депозитные и металлические счета')),
                ('active_trading', models.FileField(blank=True, null=True, upload_to='files', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='активная торговля ценными бумагами')),
                ('existing_qualifications', models.FileField(blank=True, null=True, upload_to='files', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='активная торговля ценными бумагами')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_qualifications.Investor', verbose_name='Инвестор')),
            ],
            options={
                'verbose_name_plural': 'Qualification Documents',
            },
        ),
        migrations.CreateModel(
            name='PassportData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия пользователя')),
                ('patronymic', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчетсво пользователя')),
                ('passport_number', models.CharField(max_length=12, verbose_name='Серия и номер паспорта')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('place_of_birth', models.CharField(max_length=100, verbose_name='Место рождения')),
                ('passport_issue_date', models.DateField(verbose_name='Дата выдачи пасспорта')),
                ('police_station_code', models.CharField(max_length=7, verbose_name='Код подразделения')),
                ('police_station_name', models.CharField(max_length=100, verbose_name='Кем выдан')),
                ('investor_registration_address', models.CharField(max_length=100, verbose_name='Адрес регистрации')),
                ('passport_first_sheet', models.FileField(upload_to='files', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Первый разворот паспорта')),
                ('passport_second_sheet', models.FileField(upload_to='files', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Второй разворот паспорта')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_qualifications.Investor', verbose_name='Инвестор')),
            ],
            options={
                'verbose_name_plural': 'Passport data',
                'ordering': ['passport_number'],
            },
        ),
        migrations.AddField(
            model_name='investor',
            name='qualification_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_qualifications.QualificationStatus', verbose_name='Общий статус квалификации пользователя'),
        ),
    ]
